---
- import-playbook: user.yml
- name: install java
  hosts: all
  become: yes
  tasks: 
    - name: instal java 11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes